import {TOrder, TUser} from '@/common/common.types';

export const users: TUser[] = [
  {id: 'u1', email: 'maher@wakilni.com', name: 'Maher', password: 'maher@123'},
  {id: 'u2', email: 'amin@wakilni.com', name: 'Amin', password: 'amin@123'},
];

export const orders: TOrder[] = [
  {
    id: '60585771',
    clientName: 'Wayne Enterprises',
    recipientName: 'Rami Haddad',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 3,
    notes: 'Fragile',
    status: 'Cancelled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it0_0',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-7531',
        fulfilled: false,
      },
      {
        id: 'it0_1',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-2300',
        fulfilled: false,
      },
      {
        id: 'it0_2',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-2783',
        fulfilled: false,
      },
    ],
  },
  {
    id: '83441358',
    clientName: 'Initech',
    recipientName: 'Omar T.',
    locationEn: 'Zahle - Center',
    locationAr: 'زحلة - الوسط',
    itemsCount: 3,
    notes: 'Handle with care',
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it1_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-2063',
        fulfilled: true,
      },
      {
        id: 'it1_1',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-4674',
        fulfilled: true,
      },
      {
        id: 'it1_2',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-6906',
        fulfilled: true,
      },
    ],
  },
  {
    id: '84719690',
    clientName: 'Stark Industries',
    recipientName: 'Layla B.',
    locationEn: 'Zahle - Center',
    locationAr: 'زحلة - الوسط',
    itemsCount: 2,
    notes: 'Handle with care',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it2_0',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-2966',
        fulfilled: false,
      },
      {
        id: 'it2_1',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-9875',
        fulfilled: false,
      },
    ],
  },
  {
    id: '83864611',
    clientName: 'Stark Industries',
    recipientName: 'Karim J.',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 2,
    notes: 'Deliver before noon',
    status: 'Cancelled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it3_0',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-8553',
        fulfilled: false,
      },
      {
        id: 'it3_1',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-2695',
        fulfilled: false,
      },
    ],
  },
  {
    id: '43226120',
    clientName: 'Wayne Enterprises',
    recipientName: 'Yara M.',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 2,
    notes: 'Fragile',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it4_0',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-7069',
        fulfilled: false,
      },
      {
        id: 'it4_1',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-9500',
        fulfilled: false,
      },
    ],
  },
  {
    id: '66232115',
    clientName: 'Umbrella Corp',
    recipientName: 'Omar T.',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 1,
    notes: 'Handle with care',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it5_0',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-2422',
        fulfilled: false,
      },
    ],
  },
  {
    id: '80415539',
    clientName: 'Wayne Enterprises',
    recipientName: 'Yara M.',
    locationEn: 'Zahle - Center',
    locationAr: 'زحلة - الوسط',
    itemsCount: 1,
    notes: 'Handle with care',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it6_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-5721',
        fulfilled: false,
      },
    ],
  },
  {
    id: '29055619',
    clientName: 'Globex',
    recipientName: 'Rami Haddad',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 1,
    notes: null,
    status: 'Fulfilled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it7_0',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-6933',
        fulfilled: true,
      },
    ],
  },
  {
    id: '72649638',
    clientName: 'Stark Industries',
    recipientName: 'Nada S.',
    locationEn: 'Zahle - Center',
    locationAr: 'زحلة - الوسط',
    itemsCount: 5,
    notes: 'Fragile',
    status: 'In Progress',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it8_0',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-3353',
        fulfilled: false,
      },
      {
        id: 'it8_1',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-7834',
        fulfilled: false,
      },
      {
        id: 'it8_2',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-6247',
        fulfilled: false,
      },
      {
        id: 'it8_3',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-6811',
        fulfilled: false,
      },
      {
        id: 'it8_4',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-4749',
        fulfilled: false,
      },
    ],
  },
  {
    id: '43372884',
    clientName: 'Wayne Enterprises',
    recipientName: 'Rami Haddad',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 4,
    notes: null,
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it9_0',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-7880',
        fulfilled: false,
      },
      {
        id: 'it9_1',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-7706',
        fulfilled: false,
      },
      {
        id: 'it9_2',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-2736',
        fulfilled: false,
      },
      {
        id: 'it9_3',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-9387',
        fulfilled: false,
      },
    ],
  },
  {
    id: '34191654',
    clientName: 'Wayne Enterprises',
    recipientName: 'Layla B.',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 2,
    notes: null,
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it10_0',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-4806',
        fulfilled: false,
      },
      {
        id: 'it10_1',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-7544',
        fulfilled: false,
      },
    ],
  },
  {
    id: '83492639',
    clientName: 'Globex',
    recipientName: 'Karim J.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 1,
    notes: 'Fragile',
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it11_0',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-7373',
        fulfilled: true,
      },
    ],
  },
  {
    id: '99305864',
    clientName: 'Globex',
    recipientName: 'Karim J.',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 5,
    notes: 'Fragile',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it12_0',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-8039',
        fulfilled: false,
      },
      {
        id: 'it12_1',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-7726',
        fulfilled: false,
      },
      {
        id: 'it12_2',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-1208',
        fulfilled: false,
      },
      {
        id: 'it12_3',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-7380',
        fulfilled: false,
      },
      {
        id: 'it12_4',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-6070',
        fulfilled: false,
      },
    ],
  },
  {
    id: '83623876',
    clientName: 'Initech',
    recipientName: 'Omar T.',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 3,
    notes: 'Fragile',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it13_0',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-6451',
        fulfilled: false,
      },
      {
        id: 'it13_1',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-8715',
        fulfilled: false,
      },
      {
        id: 'it13_2',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-5945',
        fulfilled: false,
      },
    ],
  },
  {
    id: '55132541',
    clientName: 'Umbrella Corp',
    recipientName: 'Omar T.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 2,
    notes: 'Handle with care',
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it14_0',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-4375',
        fulfilled: true,
      },
      {
        id: 'it14_1',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-9362',
        fulfilled: true,
      },
    ],
  },
  {
    id: '92695420',
    clientName: 'Wayne Enterprises',
    recipientName: 'Yara M.',
    locationEn: 'Zahle - Center',
    locationAr: 'زحلة - الوسط',
    itemsCount: 5,
    notes: 'Handle with care',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it15_0',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-9610',
        fulfilled: false,
      },
      {
        id: 'it15_1',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-1571',
        fulfilled: false,
      },
      {
        id: 'it15_2',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-1259',
        fulfilled: false,
      },
      {
        id: 'it15_3',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-7955',
        fulfilled: false,
      },
      {
        id: 'it15_4',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-8423',
        fulfilled: false,
      },
    ],
  },
  {
    id: '63149131',
    clientName: 'Stark Industries',
    recipientName: 'Karim J.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 1,
    notes: 'Fragile',
    status: 'In Progress',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it16_0',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-1837',
        fulfilled: false,
      },
    ],
  },
  {
    id: '39681623',
    clientName: 'ACME Co.',
    recipientName: 'Mira K.',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 3,
    notes: 'Handle with care',
    status: 'Fulfilled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it17_0',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-6079',
        fulfilled: true,
      },
      {
        id: 'it17_1',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-5158',
        fulfilled: true,
      },
      {
        id: 'it17_2',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-7137',
        fulfilled: true,
      },
    ],
  },
  {
    id: '55470860',
    clientName: 'Globex',
    recipientName: 'Rami Haddad',
    locationEn: 'Beirut - Achrafieh',
    locationAr: 'بيروت - الأشرفية',
    itemsCount: 3,
    notes: 'Fragile',
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it18_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-9413',
        fulfilled: false,
      },
      {
        id: 'it18_1',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-6527',
        fulfilled: false,
      },
      {
        id: 'it18_2',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-2815',
        fulfilled: false,
      },
    ],
  },
  {
    id: '63338884',
    clientName: 'Umbrella Corp',
    recipientName: 'Yara M.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 3,
    notes: null,
    status: 'Cancelled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it19_0',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-5013',
        fulfilled: false,
      },
      {
        id: 'it19_1',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-3546',
        fulfilled: false,
      },
      {
        id: 'it19_2',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-8757',
        fulfilled: false,
      },
    ],
  },
  {
    id: '82834196',
    clientName: 'Stark Industries',
    recipientName: 'Fadi N.',
    locationEn: 'Beirut - Achrafieh',
    locationAr: 'بيروت - الأشرفية',
    itemsCount: 1,
    notes: 'Handle with care',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it20_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-1198',
        fulfilled: false,
      },
    ],
  },
  {
    id: '47813196',
    clientName: 'Stark Industries',
    recipientName: 'Layla B.',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 1,
    notes: null,
    status: 'In Progress',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it21_0',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-4829',
        fulfilled: false,
      },
    ],
  },
  {
    id: '40727465',
    clientName: 'Initech',
    recipientName: 'Fadi N.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 3,
    notes: null,
    status: 'Cancelled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it22_0',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-7271',
        fulfilled: false,
      },
      {
        id: 'it22_1',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-5726',
        fulfilled: false,
      },
      {
        id: 'it22_2',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-8647',
        fulfilled: false,
      },
    ],
  },
  {
    id: '39271157',
    clientName: 'ACME Co.',
    recipientName: 'Rami Haddad',
    locationEn: 'Beirut - Achrafieh',
    locationAr: 'بيروت - الأشرفية',
    itemsCount: 1,
    notes: 'Deliver before noon',
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it23_0',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-6227',
        fulfilled: true,
      },
    ],
  },
  {
    id: '89327077',
    clientName: 'Initech',
    recipientName: 'Rami Haddad',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 2,
    notes: 'Handle with care',
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it24_0',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-4303',
        fulfilled: false,
      },
      {
        id: 'it24_1',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-4743',
        fulfilled: false,
      },
    ],
  },
  {
    id: '33336503',
    clientName: 'ACME Co.',
    recipientName: 'Mira K.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 4,
    notes: 'Fragile',
    status: 'Fulfilled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it25_0',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-9904',
        fulfilled: true,
      },
      {
        id: 'it25_1',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-1136',
        fulfilled: true,
      },
      {
        id: 'it25_2',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-7316',
        fulfilled: true,
      },
      {
        id: 'it25_3',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-6228',
        fulfilled: true,
      },
    ],
  },
  {
    id: '10834488',
    clientName: 'Wayne Enterprises',
    recipientName: 'Omar T.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 4,
    notes: null,
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it26_0',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-2888',
        fulfilled: false,
      },
      {
        id: 'it26_1',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-1708',
        fulfilled: false,
      },
      {
        id: 'it26_2',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-3726',
        fulfilled: false,
      },
      {
        id: 'it26_3',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-5044',
        fulfilled: false,
      },
    ],
  },
  {
    id: '32734066',
    clientName: 'Wayne Enterprises',
    recipientName: 'Fadi N.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 4,
    notes: 'Handle with care',
    status: 'In Progress',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it27_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-4530',
        fulfilled: false,
      },
      {
        id: 'it27_1',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-6190',
        fulfilled: false,
      },
      {
        id: 'it27_2',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-9308',
        fulfilled: false,
      },
      {
        id: 'it27_3',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-5134',
        fulfilled: false,
      },
    ],
  },
  {
    id: '71140821',
    clientName: 'Umbrella Corp',
    recipientName: 'Rami Haddad',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 5,
    notes: 'Deliver before noon',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it28_0',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-8118',
        fulfilled: false,
      },
      {
        id: 'it28_1',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-7891',
        fulfilled: false,
      },
      {
        id: 'it28_2',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-3337',
        fulfilled: false,
      },
      {
        id: 'it28_3',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-7395',
        fulfilled: false,
      },
      {
        id: 'it28_4',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-9157',
        fulfilled: false,
      },
    ],
  },
  {
    id: '41953738',
    clientName: 'Globex',
    recipientName: 'Layla B.',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 4,
    notes: 'Fragile',
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it29_0',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-4738',
        fulfilled: true,
      },
      {
        id: 'it29_1',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-2520',
        fulfilled: true,
      },
      {
        id: 'it29_2',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-8172',
        fulfilled: true,
      },
      {
        id: 'it29_3',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-7763',
        fulfilled: true,
      },
    ],
  },
  {
    id: '88602268',
    clientName: 'Umbrella Corp',
    recipientName: 'Nada S.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 3,
    notes: null,
    status: 'Fulfilled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it30_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-3599',
        fulfilled: true,
      },
      {
        id: 'it30_1',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-8755',
        fulfilled: true,
      },
      {
        id: 'it30_2',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-2445',
        fulfilled: true,
      },
    ],
  },
  {
    id: '41839466',
    clientName: 'ACME Co.',
    recipientName: 'Mira K.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 1,
    notes: 'Deliver before noon',
    status: 'In Progress',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it31_0',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-8065',
        fulfilled: false,
      },
    ],
  },
  {
    id: '51583705',
    clientName: 'Umbrella Corp',
    recipientName: 'Layla B.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 3,
    notes: 'Fragile',
    status: 'Fulfilled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it32_0',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-8524',
        fulfilled: true,
      },
      {
        id: 'it32_1',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-3560',
        fulfilled: true,
      },
      {
        id: 'it32_2',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-1324',
        fulfilled: true,
      },
    ],
  },
  {
    id: '61239174',
    clientName: 'Initech',
    recipientName: 'Layla B.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 2,
    notes: null,
    status: 'In Progress',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it33_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-2120',
        fulfilled: false,
      },
      {
        id: 'it33_1',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-4828',
        fulfilled: false,
      },
    ],
  },
  {
    id: '49829549',
    clientName: 'ACME Co.',
    recipientName: 'Mira K.',
    locationEn: 'Beirut - Achrafieh',
    locationAr: 'بيروت - الأشرفية',
    itemsCount: 3,
    notes: null,
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it34_0',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-8258',
        fulfilled: false,
      },
      {
        id: 'it34_1',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-7095',
        fulfilled: false,
      },
      {
        id: 'it34_2',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-4991',
        fulfilled: false,
      },
    ],
  },
  {
    id: '67768590',
    clientName: 'Stark Industries',
    recipientName: 'Yara M.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 2,
    notes: null,
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it35_0',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-1649',
        fulfilled: false,
      },
      {
        id: 'it35_1',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-9459',
        fulfilled: false,
      },
    ],
  },
  {
    id: '53528609',
    clientName: 'Umbrella Corp',
    recipientName: 'Nada S.',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 4,
    notes: 'Handle with care',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it36_0',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-5319',
        fulfilled: false,
      },
      {
        id: 'it36_1',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-6523',
        fulfilled: false,
      },
      {
        id: 'it36_2',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-7758',
        fulfilled: false,
      },
      {
        id: 'it36_3',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-6934',
        fulfilled: false,
      },
    ],
  },
  {
    id: '60947560',
    clientName: 'ACME Co.',
    recipientName: 'Nada S.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 4,
    notes: 'Fragile',
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it37_0',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-6952',
        fulfilled: true,
      },
      {
        id: 'it37_1',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-2210',
        fulfilled: true,
      },
      {
        id: 'it37_2',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-3104',
        fulfilled: true,
      },
      {
        id: 'it37_3',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-6357',
        fulfilled: true,
      },
    ],
  },
  {
    id: '14908547',
    clientName: 'Umbrella Corp',
    recipientName: 'Layla B.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 2,
    notes: 'Fragile',
    status: 'In Progress',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it38_0',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-5290',
        fulfilled: false,
      },
      {
        id: 'it38_1',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-4600',
        fulfilled: false,
      },
    ],
  },
  {
    id: '80628303',
    clientName: 'Wayne Enterprises',
    recipientName: 'Karim J.',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 3,
    notes: 'Fragile',
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it39_0',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-3282',
        fulfilled: false,
      },
      {
        id: 'it39_1',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-4342',
        fulfilled: false,
      },
      {
        id: 'it39_2',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-6374',
        fulfilled: false,
      },
    ],
  },
  {
    id: '75944836',
    clientName: 'Initech',
    recipientName: 'Mira K.',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 5,
    notes: null,
    status: 'Cancelled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it40_0',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-2001',
        fulfilled: false,
      },
      {
        id: 'it40_1',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-4635',
        fulfilled: false,
      },
      {
        id: 'it40_2',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-8575',
        fulfilled: false,
      },
      {
        id: 'it40_3',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-7995',
        fulfilled: false,
      },
      {
        id: 'it40_4',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-8347',
        fulfilled: false,
      },
    ],
  },
  {
    id: '24576019',
    clientName: 'Umbrella Corp',
    recipientName: 'Layla B.',
    locationEn: 'Beirut - Achrafieh',
    locationAr: 'بيروت - الأشرفية',
    itemsCount: 3,
    notes: null,
    status: 'In Progress',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it41_0',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-9147',
        fulfilled: false,
      },
      {
        id: 'it41_1',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-8298',
        fulfilled: false,
      },
      {
        id: 'it41_2',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-2143',
        fulfilled: false,
      },
    ],
  },
  {
    id: '38738539',
    clientName: 'Stark Industries',
    recipientName: 'Karim J.',
    locationEn: 'Zahle - Center',
    locationAr: 'زحلة - الوسط',
    itemsCount: 5,
    notes: 'Deliver before noon',
    status: 'Cancelled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it42_0',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-5275',
        fulfilled: false,
      },
      {
        id: 'it42_1',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-8061',
        fulfilled: false,
      },
      {
        id: 'it42_2',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-4963',
        fulfilled: false,
      },
      {
        id: 'it42_3',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-1575',
        fulfilled: false,
      },
      {
        id: 'it42_4',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-7478',
        fulfilled: false,
      },
    ],
  },
  {
    id: '30060740',
    clientName: 'Initech',
    recipientName: 'Mira K.',
    locationEn: 'Sidon - Corniche',
    locationAr: 'صيدا - الكورنيش',
    itemsCount: 2,
    notes: 'Deliver before noon',
    status: 'Ready for Fulfillment',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it43_0',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-3581',
        fulfilled: false,
      },
      {
        id: 'it43_1',
        name: 'Watch',
        size: null,
        color: 'Silver',
        expectedSerial: 'WATCH-NA-S-4772',
        fulfilled: false,
      },
    ],
  },
  {
    id: '19239963',
    clientName: 'Globex',
    recipientName: 'Nada S.',
    locationEn: 'Beirut - Achrafieh',
    locationAr: 'بيروت - الأشرفية',
    itemsCount: 2,
    notes: null,
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it44_0',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-9874',
        fulfilled: true,
      },
      {
        id: 'it44_1',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-9396',
        fulfilled: true,
      },
    ],
  },
  {
    id: '59666069',
    clientName: 'Umbrella Corp',
    recipientName: 'Omar T.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 5,
    notes: 'Fragile',
    status: 'In Progress',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it45_0',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-8683',
        fulfilled: false,
      },
      {
        id: 'it45_1',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-9115',
        fulfilled: false,
      },
      {
        id: 'it45_2',
        name: 'Shoes',
        size: '42',
        color: 'White',
        expectedSerial: 'SHOES-42-W-6361',
        fulfilled: false,
      },
      {
        id: 'it45_3',
        name: 'Bag',
        size: 'One',
        color: 'Black',
        expectedSerial: 'BAG-One-B-9664',
        fulfilled: false,
      },
      {
        id: 'it45_4',
        name: 'Sunglasses',
        size: null,
        color: 'Black',
        expectedSerial: 'SUNGLASSES-NA-B-3182',
        fulfilled: false,
      },
    ],
  },
  {
    id: '60045915',
    clientName: 'Umbrella Corp',
    recipientName: 'Rami Haddad',
    locationEn: 'Byblos - Port',
    locationAr: 'جبيل - المرفأ',
    itemsCount: 3,
    notes: 'Fragile',
    status: 'Fulfilled',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it46_0',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-6492',
        fulfilled: true,
      },
      {
        id: 'it46_1',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-8763',
        fulfilled: true,
      },
      {
        id: 'it46_2',
        name: 'T-Shirt',
        size: 'L',
        color: 'Blue',
        expectedSerial: 'T-SHIRT-L-B-5231',
        fulfilled: true,
      },
    ],
  },
  {
    id: '40293072',
    clientName: 'Stark Industries',
    recipientName: 'Yara M.',
    locationEn: 'Tyre - Old Town',
    locationAr: 'صور - المدينة القديمة',
    itemsCount: 2,
    notes: 'Handle with care',
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it47_0',
        name: 'Dress',
        size: 'M',
        color: 'Green',
        expectedSerial: 'DRESS-M-G-8554',
        fulfilled: false,
      },
      {
        id: 'it47_1',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-8891',
        fulfilled: false,
      },
    ],
  },
  {
    id: '35924109',
    clientName: 'Initech',
    recipientName: 'Yara M.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 2,
    notes: null,
    status: 'Cancelled',
    assignedToUserId: 'u2',
    items: [
      {
        id: 'it48_0',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-4757',
        fulfilled: false,
      },
      {
        id: 'it48_1',
        name: 'Cap',
        size: 'M',
        color: 'Red',
        expectedSerial: 'CAP-M-R-1337',
        fulfilled: false,
      },
    ],
  },
  {
    id: '11656146',
    clientName: 'Initech',
    recipientName: 'Yara M.',
    locationEn: 'Tripoli - Mina',
    locationAr: 'طرابلس - الميناء',
    itemsCount: 3,
    notes: null,
    status: 'In Progress',
    assignedToUserId: 'u1',
    items: [
      {
        id: 'it49_0',
        name: 'Jacket',
        size: 'XL',
        color: 'Brown',
        expectedSerial: 'JACKET-XL-B-5119',
        fulfilled: false,
      },
      {
        id: 'it49_1',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-4614',
        fulfilled: false,
      },
      {
        id: 'it49_2',
        name: 'Jeans',
        size: '32',
        color: 'Black',
        expectedSerial: 'JEANS-32-B-2886',
        fulfilled: false,
      },
    ],
  },
];
